# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(db_index=True, max_length=200)),
                (
                    "buyer_type",
                    models.CharField(
                        choices=[
                            ("RETAILER", "Corporate Retailer"),
                            ("PROCESSOR", "Food Processor"),
                            ("EXPORTER", "Export House"),
                            ("FPO_AGGREGATOR", "FPO Aggregator"),
                            ("WHOLESALER", "Direct Wholesaler"),
                            ("INSTITUTION", "Institutional Buyer"),
                        ],
                        db_index=True,
                        default="RETAILER",
                        max_length=30,
                    ),
                ),
                ("procurement_hub", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        db_index=True, default="Maharashtra", max_length=100
                    ),
                ),
                (
                    "distance_km_default",
                    models.DecimalField(decimal_places=1, default=28.0, max_digits=6),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified Buyer"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="VERIFIED",
                        max_length=20,
                    ),
                ),
                ("reliability_score", models.IntegerField(default=95)),
                (
                    "payment_reliability_score",
                    models.DecimalField(decimal_places=2, default=99.0, max_digits=5),
                ),
                ("completed_transactions", models.IntegerField(default=120)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.9, max_digits=3),
                ),
                ("reviews_count", models.IntegerField(default=50)),
                (
                    "payment_terms",
                    models.CharField(default="Instant Digital (T+0)", max_length=100),
                ),
                ("pickup_service_available", models.BooleanField(default=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "minimum_quality",
                    models.CharField(default="Grade A (Export/Premium)", max_length=50),
                ),
                ("delivery_location", models.CharField(max_length=255)),
                ("required_by", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("CLOSED", "Closed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="buyers.buyer",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_demands",
                        to="crops.crop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
