# Generated by Django 5.2.17 on 2026-08-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buyer",
            options={"ordering": ["id"]},
        ),
    ]
