# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MANDI", "APMC Regulated Mandi"),
                            ("PROCESSOR", "Food Processing Unit"),
                            (
                                "INSTITUTIONAL_BUYER",
                                "Corporate / Retail Procurement Hub",
                            ),
                            ("DIGITAL_MARKET", "Digital Spot / E-Market"),
                        ],
                        db_index=True,
                        default="MANDI",
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        db_index=True, default="Maharashtra", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "distance_km_default",
                    models.DecimalField(decimal_places=1, default=25.0, max_digits=6),
                ),
                (
                    "market_fee_percent",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
                (
                    "weighment_cost_per_kg",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
                ),
                (
                    "unloading_cost_per_kg",
                    models.DecimalField(decimal_places=2, default=0.15, max_digits=4),
                ),
                ("payment_cycle_days", models.IntegerField(default=2)),
                ("reliability_score", models.IntegerField(default=85)),
                (
                    "operating_hours",
                    models.CharField(default="5:00 AM - 2:00 PM", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "modal_price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
                ),
                (
                    "arrival_volume",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("arrival_trend", models.CharField(default="steady", max_length=20)),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_prices",
                        to="crops.crop",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "crop"],
                "indexes": [
                    models.Index(
                        fields=["crop", "market", "date"],
                        name="markets_mar_crop_id_265ac1_idx",
                    ),
                    models.Index(
                        fields=["market", "date"], name="markets_mar_market__39d89b_idx"
                    ),
                    models.Index(
                        fields=["crop", "date"], name="markets_mar_crop_id_f2545a_idx"
                    ),
                ],
            },
        ),
    ]
