# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "quality_grade",
                    models.CharField(default="Grade A (Export/Premium)", max_length=50),
                ),
                ("recommended_destination_name", models.CharField(max_length=255)),
                (
                    "recommended_destination_type",
                    models.CharField(default="BUYER", max_length=50),
                ),
                (
                    "destination_location",
                    models.CharField(default="Nashik Hub", max_length=255),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=1, default=28.0, max_digits=6),
                ),
                (
                    "expected_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_transport_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_transport_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "estimated_storage_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "estimated_net_realization",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_net_realization_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "recommended_selling_window",
                    models.CharField(
                        default="Sell within the next 2–3 days (Peak realization window)",
                        max_length=150,
                    ),
                ),
                ("confidence_score", models.IntegerField(default=91)),
                ("explanation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="crops.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
