# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_location", models.CharField(max_length=255)),
                ("village", models.CharField(blank=True, max_length=100, null=True)),
                ("taluka", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(db_index=True, max_length=100)),
                (
                    "state",
                    models.CharField(
                        db_index=True, default="Maharashtra", max_length=100
                    ),
                ),
                (
                    "farm_size_acres",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
                ),
                (
                    "organization_fpo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fpo_member_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "KYC Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="VERIFIED",
                        max_length=20,
                    ),
                ),
                ("trust_score", models.IntegerField(default=90)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=4.8, max_digits=3),
                ),
                ("completed_transactions", models.IntegerField(default=0)),
                ("bank_account_linked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmerCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "available_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("harvest_date", models.DateField()),
                (
                    "expected_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("GRADE_A", "Grade A (Export / Premium)"),
                            ("GRADE_B", "Grade B (Supermarket / Standard)"),
                            ("GRADE_C", "Grade C (Processing / Bulk)"),
                        ],
                        default="GRADE_A",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "moisture_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_harvests",
                        to="crops.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvests",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
        ),
    ]
