# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=150, unique=True)),
                ("capacity_kg", models.IntegerField(default=750)),
                (
                    "base_rate_per_km",
                    models.DecimalField(decimal_places=2, default=14.0, max_digits=6),
                ),
                (
                    "loading_unloading_cost",
                    models.DecimalField(decimal_places=2, default=350.0, max_digits=6),
                ),
                ("estimated_speed_kmph", models.IntegerField(default=40)),
                (
                    "driver_rating",
                    models.DecimalField(decimal_places=2, default=4.85, max_digits=3),
                ),
                (
                    "availability",
                    models.CharField(default="Available Immediately", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("distance_km", models.DecimalField(decimal_places=1, max_digits=6)),
                (
                    "quantity_kg",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                (
                    "vehicle_type",
                    models.CharField(default="Tata Ace (Chhota Hathi)", max_length=150),
                ),
                (
                    "driver_name",
                    models.CharField(default="Kishor Gaikwad", max_length=100),
                ),
                (
                    "driver_phone",
                    models.CharField(default="+91 97654 32109", max_length=20),
                ),
                (
                    "vehicle_number",
                    models.CharField(default="MH-15-EG-4412", max_length=50),
                ),
                (
                    "estimated_transport_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cost_per_kg", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("DRIVER_ASSIGNED", "Driver Assigned"),
                            ("LOADED", "Loaded at Farm Gate"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered at Hub / Market"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRIVER_ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "estimated_delivery_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_bookings",
                        to="lots.digitallot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
