# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("crops", "0001_initial"),
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("GRADE_A", "Grade A (Export/Premium)"),
                            ("GRADE_B", "Grade B (Supermarket/Standard)"),
                            ("GRADE_C", "Grade C (Processing/Bulk)"),
                        ],
                        default="GRADE_A",
                        max_length=20,
                    ),
                ),
                ("harvest_date", models.DateField()),
                ("asking_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=255)),
                ("farm_pincode", models.CharField(default="422202", max_length=10)),
                (
                    "moisture_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published / Active"),
                            ("OFFER_RECEIVED", "Offer Received"),
                            ("NEGOTIATING", "Negotiating"),
                            ("DEAL_LOCKED", "Deal Locked"),
                            ("IN_TRANSIT", "In Transit"),
                            ("SOLD", "Settled & Sold"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="crops.crop",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_lots",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=150, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lots.digitallot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimated_transport_per_kg",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=6),
                ),
                (
                    "estimated_net_realization_per_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "payment_terms",
                    models.CharField(default="Instant Digital (T+0)", max_length=100),
                ),
                ("pickup_offered", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("ACCEPTED", "Accepted & Deal Locked"),
                            ("REJECTED", "Rejected"),
                            ("COUNTERED", "Counter Proposed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "counter_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_made",
                        to="buyers.buyer",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="lots.digitallot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
