# Generated by Django 5.2.17 on 2026-08-23 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitallot",
            name="harvest_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="digitallot",
            name="location",
            field=models.CharField(default="Farm Gate, Nashik", max_length=255),
        ),
    ]
