# Generated by Django 5.2.17 on 2026-08-23 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("farmers", "0001_initial"),
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreed_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transport_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "storage_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_realization",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("IN_ESCROW", "Secured in Safe Escrow"),
                            ("RELEASED_TO_BANK", "Released to Bank"),
                            ("COMPLETED", "Settlement Completed"),
                            ("DISPUTED", "Under Dispute Review"),
                        ],
                        db_index=True,
                        default="IN_ESCROW",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("DEAL_LOCKED", "Deal Locked"),
                            ("PICKUP_SCHEDULED", "Pickup Scheduled"),
                            ("IN_TRANSIT", "In Transit"),
                            ("INSPECTED", "Quality & Weighment Verified"),
                            ("SETTLED", "Settled & Paid"),
                        ],
                        db_index=True,
                        default="DEAL_LOCKED",
                        max_length=30,
                    ),
                ),
                ("utr_number", models.CharField(blank=True, max_length=100, null=True)),
                ("timeline", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_transactions",
                        to="buyers.buyer",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_transactions",
                        to="farmers.farmerprofile",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="lots.digitallot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
