# Generated by Django 5.2.17 on 2026-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("local_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "crop_category",
                    models.CharField(
                        choices=[
                            ("VEGETABLES", "Vegetables"),
                            ("GRAINS", "Grains & Cereals"),
                            ("PULSES", "Pulses"),
                            ("OILSEEDS", "Oilseeds"),
                            ("FRUITS", "Fruits"),
                            ("CASH_CROPS", "Cash Crops"),
                        ],
                        db_index=True,
                        default="VEGETABLES",
                        max_length=30,
                    ),
                ),
                ("unit", models.CharField(default="kg", max_length=20)),
                ("icon", models.CharField(default="🌱", max_length=10)),
                ("default_shelf_life_days", models.IntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
